rails_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # get 'users/show' => 'users#show'
  resources :users, only: [:show]
  get '/mypage' => 'users#mypage'
  
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  

  # Defines the root path route ("/")
  root "questions#index"
  resources :questions do
    resources :answers do
      put :add_good, on: :member
      put :add_bestanswer, on: :member
    end
  end

  
end

rails_project/app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: { minimum: 5 }

  def best_answer
    if self.bestanswer_id.nil?
      return nil
    end
    Answer.find(self.bestanswer_id)
  end
end

rails_project/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  # 質問一覧表示
  def index
    @questions = Question.all
  end

  # 質問詳細ページ表示
  def show
    @question = Question.find(params[:id])
    if id = @question.bestanswer_id
      @bestanswer = @question.answers.find(id)
      @answer = @question.answers.where('id != ?', id).order(good: :desc)
      render 'questions/show/resolved'
    else
      render 'questions/show/unresolved'
    end
  end

  # 質問の作成
  def new
    @question = Question.new
  end

  # 質問の登録
  def create
    # Questionモデルを初期化
    @question = current_user.questions.new question_params
    # QuestionモデルをDBへ保存
    if @question.save
      # showへリダイレクト
      redirect_to @question
    else
      render 'new', status: :unprocessable_entity # エラーコード422で返す
    end
  end

  # 質問の編集
  def edit
    @question = Question.find(params[:id])
  end

  # 質問の更新
  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  # 質問の削除
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :name, :content)
  end
end

rails_project/app/helpers/questions_helper.rb
module QuestionsHelper
end

rails_project/app/views/questions/_answer.erb
<turbo-frame id=<%= "answer_#{answer.id}" %>>

    <div class="show-box">
        <div class="show-box-name">
            <div>氏名</div> 
            <div><%= answer.name %></div>
        </div>
        <div class="show-box-contents">
            <div>回答内容</div>
            <div><%= safe_join(answer.content.split("\n"), tag(:br)) %></div>
        </div>
    </div>
    <div class="show-footer">
        <div>
            <%= link_to add_bestanswer_question_answer_path(question_id, answer.id),
                data: { turbo_method: 'put' } do %>
                <button type="button" class="btn btn-primary">ベストアンサーに登録する</button>
            <% end %>
        </div>
        <div>
            <%= link_to add_good_question_answer_path(question_id, answer.id),
                data: { turbo_method: 'put' },remote: true do %>
                いいね
            <% end %>
        </div>
        <%= tag.div class: "image_good"%>
        <div>
            <%= answer.good %>
        </div>
        <div>
            <%= link_to '削除', [answer.question, answer],
                data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?'} %>
        </div>
    </div>
</turbo-frame>

rails_project/app/views/questions/_form.html.erb
<%= form_with model: @question do |form| %>
    <% if @question.errors.any? %>
        <div>
            <ul>
                <% @question.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= form.label :表題 %><br>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :氏名 %><br>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :質問内容 %><br>
        <%= form.text_area :content %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

rails_project/app/views/questions/edit.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'questions/edit',"data-turbo-track": "reload" %>
<% end %>

<h1>編集</h1>
<%= render partial: 'form' %>

<body>
<div class="class1">
<%= image_tag 'edit.jpg' ,size: '400x200',align: '500x200'%>
</div>
</body>

rails_project/app/views/questions/index.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'questions/index', "data-turbo-track": "reload" %>
<% end %>

<body>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
  <button
      class="nav-link active"
      id="resolved-tab"
      data-bs-toggle="tab"
      data-bs-target="#resolved"
      type="button"
      role="tab"
      aria-controls="resolved"
      aria-selected="true"
    >
      未解決
    </button>
  </li>
  <li class="nav-item" role="presentation">
  <button
      class="nav-link"
      id="profile-tab"
      data-bs-toggle="tab"
      data-bs-target="#unsolved"
      type="button"
      role="tab"
      aria-controls="unsolved"
      aria-selected="false"
    >
      解決
  </button>
  </li>
  </ul>

<div class="tab-content" id="myTabContent">
  <div
    class="tab-pane fade show active"
    id="resolved"
    role="tabpanel"
    aria-labelledby="resolved-tab"
  >
<br>
<h1>質問一覧</h1>

<% @questions.each do |question| %>
<% if !question.bestanswer_id %>
<table>
    <tr>
        <td>
            <table>
                <tr>
                    <td width="30"></td>
                    <td width="60">質問：</td>
                    <td width="460"><%= question.title %></td>
                    <td width="200"></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td width="30"></td>
                    <td width="60">内容：</td>
                    <td width="460"><%= question.content %></td>
                    <td width="200"></td>
                    <td>from . </td>
                    <td width="150"><%= question.name %></td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td><%= link_to question_path(question) do %> <button class="btn btn-secondary btn-lg show" >詳細</button><%end%></td><td></td>
                    <td><%= link_to edit_question_path(question) do %> <button class="btn btn-secondary btn-lg edit" >編集</button><%end%></td><td></td>
                    <td><%= link_to question_path(question), data: 
                        {turbo_method: 'delete', turbo_confirm: '削除してもよろしいですか？' } do %><button class="btn btn-secondary btn-lg delete" >削除</button><%end%></td><td></td>
                </tr>
                
            </table>
        </td>
    </tr>
    <tr>
    <td>
    <div class="padding">
    <p class="hr"></p>
    </div>
    <p class="height"></p>
    <% end %>
    </td>
    </tr>
</table>
<% end %>


<div class="right">
<%= link_to '質問を入力', new_question_path %>
</div>

  </div>
  
  <div
    class="tab-pane fade"
    id="unsolved"
    role="tabpanel"
    aria-labelledby="unsolved-tab">　
    
    
    <h1>質問一覧</h1>
    <% @questions.each do |question| %>
    <% if question.bestanswer_id %>
<table>
    <tr>
        <td>
            <table>
                <tr>
                    <td width="30"></td>
                    <td width="60">質問：</td>
                    <td width="460"><%= question.title %></td>
                    <td width="200"></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td width="30"></td>
                    <td width="60">内容：</td>
                    <td width="460"><%= question.content %></td>
                    <td width="200"></td>
                    <td>from . </td>
                    <td width="150"><%= question.name %></td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td><%= link_to question_path(question) do %> <button class="btn btn-secondary btn-lg show" >詳細</button><%end%></td><td></td>
                    <td><%= link_to edit_question_path(question) do %> <button class="btn btn-secondary btn-lg edit" >編集</button><%end%></td><td></td>
                    <td><%= link_to question_path(question), data: 
                        {turbo_method: 'delete', turbo_confirm: '削除してもよろしいですか？' } do %><button class="btn btn-secondary btn-lg delete" >削除</button><%end%></td><td></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
        <div class="padding">
        <p class="hr"></p>
        </div>
        <p class="height"></p>
        <% end %>
        </td>
    </tr>
</table>

<% end %>

</div>
</div>
</body>

rails_project/app/views/questions/new.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'questions/new', "data-turbo-track": "reload" %>
<% end %>

<h1>新規質問作成</h1>
<%= render partial: 'form' %>

<body>
<div class="class2">
<%= image_tag 'question.jpg' ,size: '400x270',align: '500x200'%>
</div>
</body>

rails_project/app/views/questions/show.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'questions/show', "data-turbo-track": "reload" %>
<% end %>

<div class="show">
<h1 class="show-title">質問確認画面</h1>
<div class="show-container show-question">
    <div class="show-header">質問</div>
    <div class="show-box">
        <div class="show-box-name">
            <div>氏名</div> 
            <div><%= @question.name %></div>
        </div>
        <div class="show-box-title">
            <div>表題</div>
            <div><%= @question.title %></div>
        </div>
        <div class="show-box-contents">
            <div>質問内容</div> 
            <div><%= @question.content %></div>
        </div>
    </div>
</div>
 

<% @question.answers.each_with_index do |answer, i| %>
    <div class="show-container show-answer">
        <div class="show-header">回答 <span><%= i + 1 %></span></div>
            <%= render partial: "questions/answer", locals: {question_id: @question.id, answer: answer} %>
        </div>
    </div>
<% end %>

<div class="show-container show-do-answer">
     <div class="show-header">回答を入力</div>
    <%= form_with model: [@question, @question.answers.build] do |form| %>
    <div class="show-box">
        <div class="show-box-name">
            <div>氏名</div> 
            <div><%= form.text_field :name %></div>
        </div>
        <div class="show-box-contents">
            <div>回答内容</div>
            <div><%= form.text_area :content %></div>
        </div>
    </div>
    <div class="show-footer">
        <%= form.submit "追加", class: "show-add-button"%>
    </div>    
    <% end %>
</div>
<%= link_to '質問一覧に戻る', questions_path, class: "show-index-link" %>
</div>