rails_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # get 'users/show' => 'users#show'
  resources :users, only: [:show]
  get '/mypage' => 'users#mypage'
  
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  

  # Defines the root path route ("/")
  root "questions#index"
  resources :questions do
    resources :answers do
      put :add_good, on: :member
      put :add_bestanswer, on: :member
    end
  end

  
end

rails_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :css %>
    
  </head>

  <body>
    <header>
      <nav>
          <% if user_signed_in? %>

            <%= link_to 'よしきまかせる', mypage_path %>
            <%= link_to 'プロフィール変更', edit_user_registration_path %>
            <%= link_to 'ログアウト',destroy_user_session_path , method: :delete %>
          <% else %>
            <%= link_to 'サインアップ', new_user_registration_path %>
            <%= link_to 'ログイン', new_user_session_path %>
          <% end %>
      </nav>
    </header> 
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <header class="header_2">
      
      <div class="header_3">
      <%= image_tag 'FFF.PNG' ,size: '130x130'%>
      </div>
      
      <div class="header_1">
        <h3>質問箱</h3>
      </div>
      
      <div class="header_4"></div>
      
     </header>
     
    <!--<header class="header_2">-->
    <!--<header>-->
    <!--  <table>-->
    <!--    <tr>-->
    <!--      <td width="50"></td>-->
    <!--      <td > <%= image_tag 'FFF.PNG' ,size: '150x150'%> </td>-->
    <!--      <td width="360"></td>-->
    <!--      <td > <h1 class="header_1"> 質問箱　</h1> </td>-->
    <!--      <td width="500"></td>-->
    <!--    </tr>-->
    <!--  </tabel>-->
    <!--</header>  -->
    
    <%= yield %>
  </body>
</html>