rails_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # get 'users/show' => 'users#show'
  resources :users, only: [:show]
  get '/mypage' => 'users#mypage'
  
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  

  # Defines the root path route ("/")
  root "questions#index"
  resources :questions do
    resources :answers do
      put :add_good, on: :member
      put :add_bestanswer, on: :member
    end
  end

  
end

rails_project/app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  has_one_attached :avatar      
end

rails_project/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

rails_project/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

rails_project/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

rails_project/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(configure_sign_up_params)
    if @user.save
      sign_in(@user)
      redirect_to # 任意のパス
    else
      render 'new'
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :avatar
    ])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end

  def configure_sign_up_params
    params.require(:user).permit(:name, :email, :password)
  end
end

rails_project/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

rails_project/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

rails_project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show]
  before_action :authenticate_user!, only: [:mypage]
  def show
    # redirect_to user_path(current_user)
  end
  
  def mypage
    redirect_to user_path(current_user)
    # user = User.find(params[:id])
  end
  
  
  private

  def set_user
    @user = User.find(params[:id])
  end
  
end

rails_project/app/helpers/users_helper.rb
module UsersHelper
end

rails_project/app/views/users/show.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'users/show', "data-turbo-track": "reload" %>
<% end %>
    <div class="container">
        <div class="profile border-bottom">
            <div>
                <% if @user.avatar.attached?%>
                    <%= image_tag @user.avatar, class:'profile-image' %> 
                <% else %>
                    <%= image_tag ("noimage.png"), class:'profile-image' %> 
                <% end %>
            </div>
            <div>
                <div class="name"><%= @user.name %></div>
                <div class="email"><%= @user.email %></div>
                <div class="comment balloon1-left">
                    <p><%= @user.comment %></p>
                </div>
            </div>
        </div>
        <div class="contents">
            <ul class="nav nav-underline justify-content-center nav-justified">
                <li class="nav-item">
                    <a id="question-tab" class="nav-link active" data-bs-toggle="tab" aria-current="page" href="javascript:void(0);">Question</a>
                </li>
                <li class="nav-item">
                    <a id="answer-tab" class="nav-link" data-bs-toggle="tab" href="javascript:void(0);">Answer</a>
                </li>
            </ul>
            <!-- カテゴリタブ -->
            <div class="category">
                <ul class="nav nav-pills justify-content-left">
                    <li class="nav-item">
                        <a class="nav-link active" data-bs-toggle="tab" aria-current="page" href="#">全て</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" href="#">回答受付中</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" href="#">回答済み</a>
                    </li>
                    <li class="sort_button dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        <a class="nav-link" href="#">
                            <%
=begin%>
 <img src="../img/sort_black_24dp.svg"> 
<%
=end%>
                        </a>
                        <ul class="sort-menu dropdown-menu">
                            <li><a class="dropdown-item" href="#">投稿日時(早い順)</a></li>
                            <li><a class="dropdown-item active" href="#">投稿日時(遅い順)</a></li>
                            <li><a class="dropdown-item" href="#">回答数(多い順)</a></li>
                            <li><a class="dropdown-item" href="#">回答数(少ない順)</a></li>
                          </ul>
                    </li>
                </ul>
            </div>

            <div class="contents-box">
                <% @user.questions.each do |question| %>
                <div class="border-bottom">
                    <div>
                        <% if question.best_answer%>
                        <%= image_tag 'bestanswer.jpeg' %>
                        <%
=begin%>
 <img src="../img/bestanswer.jpeg"> 
<%
=end%>
                        <% end %>
                    </div>
                    <div>
                        <div>
                            <a href=""><%= question.name%></a>

                        </div> 
                        <div>
                            ベストアンサー：<%= question.best_answer&.name%>
                        </div>
                        <div>
                            投稿日時：<%= question.created_at.strftime('%Y/%m/%d %H:%M')%>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>

    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
        <div class="offcanvas-header">
          <h4 class="offcanvas-title" id="offcanvasRightLabel">Menu</h4>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <div>
            <h5>プロフィール</h5>
            <ul>
                <li><a href="">プロフィールを変更</a></li>
            </ul>
            
          </div>
        </div>
    </div>
<%= link_to '質問一覧に戻る', questions_path, class: "show-index-link" %>